### ISSUE TITLE
Add on stops and dos not restart no entities added HA2023.12

### ISSUE THREAD

**Issue by burnsdewet** [martinville/solarsynk#2]
Good day I have installed your add on and all seems to start fine according to the log but no entities are added and when I return to the add on the add on is stopped.

I have uninstalled - re installed and same result.

Attached log with xxxxxx replacing sensitive data
[solarsync.txt](https://github.com/martinville/solarsynk/files/13777334/solarsync.txt)

Any guidance in resolving this issue would be welcomed

**Comment by wernervn** [comment]
I am experiencing the same behavior, it starts fine, runs once, then switches off. I have also attached my logs.
[SolarSynk.log](https://github.com/martinville/solarsynk/files/13800869/SolarSynk.log)

PS I was using the information provided in your [video](https://www.youtube.com/watch?v=d7gfSgN0l6M), which points to this repo, but I noticed that there is also a v2 repository. Which one should we be using?

Edit: v2 worked for me. Also, with version 2 the entities now contain the serial number of the inverter, so the power flow card values have to be updated to reflect this.

Nice work!

**Comment by martinville** [comment]
Looks like when it tries to update the entities its failing. Most probably due to errors returned by CURL.
Usually this is caused if CURL is not able to reach the URL to your HA installation either due to 

1. Wrong IP or Port number
2. Using a Loop back IP
3. Attempting to connect using HTTP on a HA installation that is SSL enabled.
4. Attempting to connect using HTTPS via IP instead of hostname on a HA installation that is SSL enabled.
